### ISSUE TITLE
(NU1101) Unable to find package Microsoft.SymbolStore. No packages exist with this id in source(s): nuget.org

### ISSUE THREAD

**Issue by theXappy** [waf/CSharpRepl#332]
### Version

main

### What happened?

Compiling from source fails on default installations of Visual Studio (2022, but I guess all version) with this cryptic message:
```
Unable to find package Microsoft.SymbolStore. No packages exist with this id in source(s): nuget.org
```
![image](https://github.com/waf/CSharpRepl/assets/10898152/c34a80f5-2d79-4cfb-94c1-4d17ddb6403d)

Took me quite some time to figure out this package isnt' suppoused to be found on nuget.org feed, unlike the rest.
I found it's available on a secondary feed hosted by microsoft from this page:
https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/connect
The feed is:
```
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
```

There aren't any other github issues referencing this and it was very frustrating to debug.
Can you please add this (unexpected IMHO) step in either the README or as a comment in the csproj, where the nuget package is defined?
![image](https://github.com/waf/CSharpRepl/assets/10898152/59d92a33-5181-47f6-bcae-94bafa914ab3)

**Comment by waf** [comment]
Thanks for this. I think this might have to do with the recent package source mappings in visual studio. It worked before but has also recently broken for me as well. Fixing it by setting up package source mappings here: https://github.com/waf/CSharpRepl/pull/333

**Comment by waf** [comment]
This should now be resolved, please give it a try.

**Comment by theXappy** [comment]
Hey @waf 
Thanks for the quick response but it still shows the same error unless I manually add the aforementioned feed in VS's settings.
![image](https://github.com/waf/CSharpRepl/assets/10898152/ee8f945f-787c-43f3-b308-e4bc13d9f431)

I don't know much about source mapping but I'm not sure it can force the nuget package manager to download packages from sources that weren't manually entered into its preferences.
like this:
![image](https://github.com/waf/CSharpRepl/assets/10898152/2ca1ea3b-ee0b-4867-8321-ed9a31c59bf0)

**Comment by theXappy** [comment]
Scratch that.
My issue was I added the `CSharpRepl.csproj` and `CSharpRepl.Services.csproj` to a different solution without copying the `nuget.config` file that you defined in this repo.
Adding the config to the sln makes everything work.

**Comment by waf** [comment]
Great, thanks for confirming!
